
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mostafa
 */
public class Cards extends javax.swing.JFrame {

    /**
     * Creates new form Cards
     * @param caller
     * @param username
     */
    public Cards(JFrame caller, String username) throws FileNotFoundException {
        initComponents();
        this.clientUserName = username ;
        calingParent = caller ;
        
        clientCard = new CreditCard(this.clientUserName) ;
        
        expDate.setText(clientCard.getCardExpiry());
        creditLimit.setText(clientCard.getCardLimit());
        cardNumber.setText("* * * *" + clientCard.getCardNumber().substring(14) );
    }

    private Cards() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        expDate = new javax.swing.JLabel();
        creditLimit = new javax.swing.JLabel();
        creditPercentage = new javax.swing.JLabel();
        cardNumber = new javax.swing.JLabel();
        expDate2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        trackerButton = new javax.swing.JButton();
        fundTransferButton = new javax.swing.JButton();
        currencyConverterButton = new javax.swing.JButton();
        CardDetails = new javax.swing.JButton();
        CardDetails1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(375, 812));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(375, 812));
        jPanel1.setLayout(null);

        expDate.setFont(new java.awt.Font("Nexa Regular", 0, 14)); // NOI18N
        expDate.setForeground(new java.awt.Color(255, 255, 255));
        expDate.setText("04/24");
        jPanel1.add(expDate);
        expDate.setBounds(75, 285, 50, 15);

        creditLimit.setFont(new java.awt.Font("Nexa Book", 0, 16)); // NOI18N
        creditLimit.setForeground(new java.awt.Color(255, 255, 255));
        creditLimit.setText("$56,000 of $80,000");
        jPanel1.add(creditLimit);
        creditLimit.setBounds(136, 501, 200, 25);

        creditPercentage.setFont(new java.awt.Font("Nexa Bold", 0, 13)); // NOI18N
        creditPercentage.setForeground(new java.awt.Color(255, 255, 255));
        creditPercentage.setText("80%");
        jPanel1.add(creditPercentage);
        creditPercentage.setBounds(67, 490, 31, 24);

        cardNumber.setFont(new java.awt.Font("Nexa Regular", 0, 15)); // NOI18N
        cardNumber.setForeground(new java.awt.Color(255, 255, 255));
        cardNumber.setText(" . . . . 6464");
        jPanel1.add(cardNumber);
        cardNumber.setBounds(120, 130, 90, 19);

        expDate2.setFont(new java.awt.Font("Nexa Book", 0, 14)); // NOI18N
        expDate2.setForeground(new java.awt.Color(255, 255, 255));
        expDate2.setText("04/24");
        jPanel1.add(expDate2);
        expDate2.setBounds(270, 285, 50, 15);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Cards.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 375, 812);

        backButton.setText("jButton1");
        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(7, 50, 26, 26);

        homeButton.setOpaque(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(34, 757, 28, 28);

        trackerButton.setOpaque(false);
        jPanel1.add(trackerButton);
        trackerButton.setBounds(170, 757, 28, 28);

        fundTransferButton.setOpaque(false);
        fundTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fundTransferButton);
        fundTransferButton.setBounds(242, 757, 26, 24);

        currencyConverterButton.setText("jButton1");
        currencyConverterButton.setOpaque(false);
        currencyConverterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyConverterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(currencyConverterButton);
        currencyConverterButton.setBounds(313, 757, 28, 28);

        CardDetails.setText("jButton1");
        CardDetails.setOpaque(false);
        CardDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(CardDetails);
        CardDetails.setBounds(55, 97, 171, 240);

        CardDetails1.setText("jButton1");
        CardDetails1.setOpaque(false);
        jPanel1.add(CardDetails1);
        CardDetails1.setBounds(246, 97, 171, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        calingParent.show();
    }//GEN-LAST:event_backButtonActionPerformed

    private void fundTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferButtonActionPerformed
        try {
            Transfer t1 = new Transfer(this, clientUserName, clientCard) ;
            t1.show();
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fundTransferButtonActionPerformed

    private void currencyConverterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyConverterButtonActionPerformed
        CurrencyConverter c1 = new CurrencyConverter(this);
        c1.show();
        this.dispose();
    }//GEN-LAST:event_currencyConverterButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        try {
            Dashboard d1 = new Dashboard(this.clientUserName);
            d1.show();
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_homeButtonActionPerformed

    private void CardDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardDetailsActionPerformed
        try {
            CardDetails c1 = new CardDetails(clientUserName,clientCard);
            c1.show();
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Cards.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CardDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cards().setVisible(true);
            }
        });
    }

    private CreditCard clientCard ;
    private final String clientUserName;
    private final JFrame calingParent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CardDetails;
    private javax.swing.JButton CardDetails1;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JLabel creditLimit;
    private javax.swing.JLabel creditPercentage;
    private javax.swing.JButton currencyConverterButton;
    private javax.swing.JLabel expDate;
    private javax.swing.JLabel expDate2;
    private javax.swing.JButton fundTransferButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton trackerButton;
    // End of variables declaration//GEN-END:variables
}
