/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mostafa
 */
public class CardDetails extends javax.swing.JFrame {

    /**
     * Creates new form CardDetails
     */
    public CardDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        availableBalance = new javax.swing.JLabel();
        cardNumber = new javax.swing.JLabel();
        expiryDate = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        changePin = new javax.swing.JButton();
        cardReissue = new javax.swing.JButton();
        cardLock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(375, 812));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(375, 812));
        jPanel1.setLayout(null);

        availableBalance.setFont(new java.awt.Font("Nexa Black", 0, 32)); // NOI18N
        availableBalance.setForeground(new java.awt.Color(255, 255, 255));
        availableBalance.setText("$5,000");
        jPanel1.add(availableBalance);
        availableBalance.setBounds(28, 185, 130, 40);

        cardNumber.setFont(new java.awt.Font("Nexa Black", 0, 16)); // NOI18N
        cardNumber.setForeground(new java.awt.Color(255, 255, 255));
        cardNumber.setText("2556 1234 5467 1256");
        jPanel1.add(cardNumber);
        cardNumber.setBounds(30, 255, 220, 35);

        expiryDate.setFont(new java.awt.Font("Nexa Black", 0, 16)); // NOI18N
        expiryDate.setForeground(new java.awt.Color(255, 255, 255));
        expiryDate.setText("12/24");
        jPanel1.add(expiryDate);
        expiryDate.setBounds(30, 312, 50, 35);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Cards (1).png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 375, 812);

        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(7, 50, 26, 26);

        changePin.setText("jButton1");
        changePin.setOpaque(false);
        jPanel1.add(changePin);
        changePin.setBounds(20, 480, 310, 60);

        cardReissue.setText("jButton1");
        cardReissue.setOpaque(false);
        jPanel1.add(cardReissue);
        cardReissue.setBounds(20, 590, 310, 50);

        cardLock.setText("jButton1");
        cardLock.setOpaque(false);
        jPanel1.add(cardLock);
        cardLock.setBounds(20, 700, 310, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 137, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Cards c1 = new Cards(new Dashboard());
        c1.show();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableBalance;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton cardLock;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JButton cardReissue;
    private javax.swing.JButton changePin;
    private javax.swing.JLabel expiryDate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
