
import java.awt.Color;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mostafa
 */
public class CurrencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter(JFrame caller) {
        initComponents();
        calingParent = caller ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        convertedCurrency = new javax.swing.JLabel();
        resultCurrency = new javax.swing.JLabel();
        convertingAmount = new javax.swing.JTextField();
        resultAmount = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        convertedCurrencyComboBox = new javax.swing.JComboBox<>();
        resultCurrencyComboBox = new javax.swing.JComboBox<>();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        creditCardButton = new javax.swing.JButton();
        fundTransferButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(375, 812));

        jPanel1.setPreferredSize(new java.awt.Dimension(375, 812));
        jPanel1.setLayout(null);

        convertedCurrency.setFont(new java.awt.Font("Nexa Book", 0, 18)); // NOI18N
        convertedCurrency.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        convertedCurrency.setText("Tap to Edit");
        jPanel1.add(convertedCurrency);
        convertedCurrency.setBounds(165, 186, 130, 27);

        resultCurrency.setFont(new java.awt.Font("Nexa Book", 0, 18)); // NOI18N
        resultCurrency.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        resultCurrency.setText("Tap to Edit");
        jPanel1.add(resultCurrency);
        resultCurrency.setBounds(165, 412, 130, 27);

        convertingAmount.setFont(new java.awt.Font("Nexa Regular", 0, 30)); // NOI18N
        convertingAmount.setForeground(new java.awt.Color(204, 204, 204));
        convertingAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        convertingAmount.setText("Type here");
        convertingAmount.setBorder(null);
        convertingAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                convertingAmountFocusGained(evt);
            }
        });
        convertingAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                convertingAmountKeyTyped(evt);
            }
        });
        jPanel1.add(convertingAmount);
        convertingAmount.setBounds(50, 223, 270, 40);

        resultAmount.setFont(new java.awt.Font("Nexa Regular", 0, 30)); // NOI18N
        resultAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultAmount.setText("0");
        jPanel1.add(resultAmount);
        resultAmount.setBounds(50, 449, 270, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Exchange.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 375, 812);

        calculateButton.setBorder(null);
        calculateButton.setOpaque(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(calculateButton);
        calculateButton.setBounds(32, 606, 312, 50);

        convertedCurrencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EGP", "SAR", "USD", "Euro", "UAE Dirham", "Pound Sterling", "Kuwait dinar", " " }));
        convertedCurrencyComboBox.setSelectedIndex(7);
        convertedCurrencyComboBox.setOpaque(false);
        convertedCurrencyComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                convertedCurrencyComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(convertedCurrencyComboBox);
        convertedCurrencyComboBox.setBounds(254, 186, 60, 27);

        resultCurrencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EGP", "SAR", "USD", "Euro", "UAE Dirham", "Pound Sterling", "Kuwait dinar", " " }));
        resultCurrencyComboBox.setSelectedIndex(7);
        resultCurrencyComboBox.setOpaque(false);
        resultCurrencyComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                resultCurrencyComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(resultCurrencyComboBox);
        resultCurrencyComboBox.setBounds(254, 412, 60, 27);

        homeButton.setOpaque(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(34, 757, 28, 28);

        backButton.setText("jButton1");
        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(7, 41, 26, 26);

        creditCardButton.setOpaque(false);
        creditCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(creditCardButton);
        creditCardButton.setBounds(102, 757, 28, 28);

        fundTransferButton.setOpaque(false);
        fundTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fundTransferButton);
        fundTransferButton.setBounds(242, 757, 26, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 146, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        Dashboard d1 = new Dashboard();
        d1.show();
        this.dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        calingParent.show();
    }//GEN-LAST:event_backButtonActionPerformed

    private void creditCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardButtonActionPerformed
        Cards c1 = new Cards(this) ;
        c1.show();
        this.dispose();
    }//GEN-LAST:event_creditCardButtonActionPerformed

    private void fundTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferButtonActionPerformed
        Transfer t1 = new Transfer(this) ;
        t1.show();
        this.dispose();
    }//GEN-LAST:event_fundTransferButtonActionPerformed

    private void convertedCurrencyComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_convertedCurrencyComboBoxItemStateChanged
        if(convertedCurrencyComboBox.getSelectedIndex()!=7)
        convertedCurrency.setText((String)convertedCurrencyComboBox.getSelectedItem());
    }//GEN-LAST:event_convertedCurrencyComboBoxItemStateChanged

    private void resultCurrencyComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_resultCurrencyComboBoxItemStateChanged
        if(convertedCurrencyComboBox.getSelectedIndex()!=7)
        resultCurrency.setText((String)resultCurrencyComboBox.getSelectedItem());
    }//GEN-LAST:event_resultCurrencyComboBoxItemStateChanged

    private void convertingAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_convertingAmountFocusGained
        convertingAmount.setText("");
        convertingAmount.setForeground(Color.BLACK);
    }//GEN-LAST:event_convertingAmountFocusGained

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
       resultAmount.setText( String.format("%.2f", 
                                currencyConverterCalculator.convert(Double.parseDouble(convertingAmount.getText()) ,
                                convertedCurrencyComboBox.getSelectedIndex() ,
                                resultCurrencyComboBox.getSelectedIndex()) )  );
       
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void convertingAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_convertingAmountKeyTyped
        if(! Character.isDigit(evt.getKeyChar()) )
            evt.consume();
    }//GEN-LAST:event_convertingAmountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter(null).setVisible(true);
            }
        });
    }

    private final JFrame calingParent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel convertedCurrency;
    private javax.swing.JComboBox<String> convertedCurrencyComboBox;
    private javax.swing.JTextField convertingAmount;
    private javax.swing.JButton creditCardButton;
    private javax.swing.JButton fundTransferButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultAmount;
    private javax.swing.JLabel resultCurrency;
    private javax.swing.JComboBox<String> resultCurrencyComboBox;
    // End of variables declaration//GEN-END:variables
}
