
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mostafa
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientName = new javax.swing.JLabel();
        availableBalance = new javax.swing.JLabel();
        cardNo4 = new javax.swing.JLabel();
        cashback = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        netTransactionsLabel = new javax.swing.JLabel();
        netValue = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        creditCardButton = new javax.swing.JButton();
        trackerButton = new javax.swing.JButton();
        fundTransferButton = new javax.swing.JButton();
        currencyConverterButton = new javax.swing.JButton();
        sideMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(375, 812));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        clientName.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        clientName.setForeground(new java.awt.Color(255, 255, 255));
        clientName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientName.setText("Hello, Josuke Jotaro");
        jPanel1.add(clientName);
        clientName.setBounds(30, 135, 310, 30);

        availableBalance.setFont(new java.awt.Font("Nexa Black", 0, 32)); // NOI18N
        availableBalance.setText("$12,196.00");
        jPanel1.add(availableBalance);
        availableBalance.setBounds(50, 340, 184, 40);

        cardNo4.setFont(new java.awt.Font("Nexa Black", 0, 20)); // NOI18N
        cardNo4.setForeground(new java.awt.Color(102, 102, 102));
        cardNo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardNo4.setText("2077");
        jPanel1.add(cardNo4);
        cardNo4.setBounds(255, 419, 53, 33);

        cashback.setFont(new java.awt.Font("Nexa Black", 0, 20)); // NOI18N
        cashback.setText("$220.54");
        jPanel1.add(cashback);
        cashback.setBounds(52, 577, 130, 35);

        deposit.setFont(new java.awt.Font("Nexa Black", 0, 20)); // NOI18N
        deposit.setText("$12,800.60");
        jPanel1.add(deposit);
        deposit.setBounds(218, 577, 130, 35);

        netTransactionsLabel.setFont(new java.awt.Font("Nexa Black", 0, 15)); // NOI18N
        netTransactionsLabel.setText("Net Transactions");
        jPanel1.add(netTransactionsLabel);
        netTransactionsLabel.setBounds(31, 688, 150, 30);

        netValue.setFont(new java.awt.Font("Nexa Regular", 0, 16)); // NOI18N
        netValue.setText("-$20.00");
        jPanel1.add(netValue);
        netValue.setBounds(260, 688, 67, 24);

        day.setFont(new java.awt.Font("Nexa Book", 0, 18)); // NOI18N
        day.setForeground(new java.awt.Color(51, 0, 153));
        day.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        day.setText("Tap to edit");
        jPanel1.add(day);
        day.setBounds(20, 634, 100, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/Dashboard.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 375, 812);

        jComboBox1.setFont(new java.awt.Font("Nexa Bold", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 185));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Last week", "Last month", " " }));
        jComboBox1.setSelectedIndex(3);
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setOpaque(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setLabel(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(45, 640, 100, 19);

        creditCardButton.setOpaque(false);
        creditCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(creditCardButton);
        creditCardButton.setBounds(102, 757, 28, 28);

        trackerButton.setOpaque(false);
        jPanel1.add(trackerButton);
        trackerButton.setBounds(170, 757, 28, 28);

        fundTransferButton.setOpaque(false);
        fundTransferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fundTransferButton);
        fundTransferButton.setBounds(242, 757, 26, 24);

        currencyConverterButton.setText("jButton1");
        currencyConverterButton.setOpaque(false);
        currencyConverterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyConverterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(currencyConverterButton);
        currencyConverterButton.setBounds(313, 757, 28, 28);

        sideMenu.setText("jButton4");
        sideMenu.setOpaque(false);
        sideMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideMenuActionPerformed(evt);
            }
        });
        jPanel1.add(sideMenu);
        sideMenu.setBounds(28, 23, 50, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setLabel(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setLabel
        if( jComboBox1.getSelectedIndex() != 3)
        day.setText((String)jComboBox1.getSelectedItem());
    }//GEN-LAST:event_setLabel

    private void sideMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideMenuActionPerformed
       DropdownMenu s1 = new DropdownMenu(this) ;
       s1.show();
       this.dispose();
    }//GEN-LAST:event_sideMenuActionPerformed

    private void creditCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardButtonActionPerformed
        Cards c1 = new Cards(this) ;
        c1.show();
        this.dispose();
    }//GEN-LAST:event_creditCardButtonActionPerformed

    private void fundTransferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferButtonActionPerformed
        Transfer t1 = new Transfer(this) ;
        t1.show();
        this.dispose();
    }//GEN-LAST:event_fundTransferButtonActionPerformed

    private void currencyConverterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyConverterButtonActionPerformed
        CurrencyConverter c1 = new CurrencyConverter(this);
        c1.show();
        this.dispose();
    }//GEN-LAST:event_currencyConverterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableBalance;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cardNo4;
    private javax.swing.JLabel cashback;
    private javax.swing.JLabel clientName;
    private javax.swing.JButton creditCardButton;
    private javax.swing.JButton currencyConverterButton;
    private javax.swing.JLabel day;
    private javax.swing.JLabel deposit;
    private javax.swing.JButton fundTransferButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel netTransactionsLabel;
    private javax.swing.JLabel netValue;
    private javax.swing.JButton sideMenu;
    private javax.swing.JButton trackerButton;
    // End of variables declaration//GEN-END:variables
}
